version: '3.8'

services:

  api:

  web:

  mariadb:

networks:
  public:
    external: true

  backend:
    driver: overlay
    internal: true
    driver_opts:
      encrypted: "true"
      com.docker.network.driver.mtu: 1450

volumes:
  database:
  data: